# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: MultiThreadCS Build Task

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        distribution: 'temurin'
    - name: set up the code and patch
      run: unzip patches.zip && unzip src.zip
    - name: setup、patch、build
      run: bash gradlew setup genPatches build
    - name: capture build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: build/distributions/
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Auto-Build"
        prerelease: true
        title: "CI 自动构建"
        files: |
          build/distributions/*.jar
